<?php

namespace Ofat\LaravelTranslatableRoutes\Routing;

use Illuminate\Container\Container;
use Illuminate\Contracts\Events\Dispatcher;
use Illuminate\Routing\RouteCollection;
use Illuminate\Routing\Router;
use Ofat\LaravelTranslatableRoutes\Http\Middleware\LocaleDetect;
use Ofat\LaravelTranslatableRoutes\TranslationParser;

class TranslatableRouter extends Router
{
    /**
     * Create a new Router instance.
     *
     * @param TranslationParser $translationParser
     * @param \Illuminate\Contracts\Events\Dispatcher $events
     * @param \Illuminate\Container\Container|null $container
     */
    public function __construct(
        protected TranslationParser $translationParser,
        Dispatcher $events,
        Container $container = null)
    {
        parent::__construct($events, $container);
    }

    public function addRoute($methods, $uri, $action)
    {
        $uri = $this->translationParser->processUri($uri);
        return parent::addRoute($methods, $uri, $action); // TODO: Change the autogenerated stub
    }

    public function languageGroup($routes)
    {
        foreach(config('translatable-routes.locales') as $locale)
        {
            app()->setLocale($locale);
            parent::
                name($locale.'.')
                ->prefix($locale)
                ->middleware(LocaleDetect::class)
                ->group($routes);
        }
    }
}
